"""empty message

Revision ID: a6948147127b
Revises:
Create Date: 2025-07-20 18:50:56.130325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6948147127b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Channals",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("Channal_id", sa.BigInteger(), nullable=True),
        sa.Column("Channal_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("Id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Channals")
    # ### end Alembic commands ###
